server:
  grpc:
    addr: 0.0.0.0:9990
    timeout: 2s
data:
  database:
    driver: mysql
    dsn: root:123456@tcp(127.0.0.1:3306)/mengma?charset=utf8mb4&parseTime=True&loc=Local
  clickhouse:
    addr: 127.0.0.1:49000
    db: mengma_qc
    username: default
    password:
  redis:
    addr: 127.0.0.1:6379
    password:
    db: 0
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
    login_token_timeout: 2592000s # 30 * 24 * 60 * 60
    product_token_timeout: 86400s # 1 * 24 * 60 * 60
    product_lock_timeout: 1s
    material_token_timeout: 86400s # 1 * 24 * 60 * 60
    material_lock_timeout: 1s
volcengine:
  tos:
    access_key: AKLTNDE4YTZjYmQyNTkwNDJmMmEzZTY4MmIxMzMzN2E3ZWU
    secret_key: TjJabU1UazFOak5tTWpKaU5HVTRNV0l4T0dVNU1HVTNNMkpqTnpGbU5USQ==
    product:
      endpoint: https://tos-cn-beijing.volces.com
      url: https://company.static.mengma.cn
      sub_folder: 40cad7891eb709fc
      region: cn-beijing
      bucket_name: company-mengma
    material:
      endpoint: https://tos-cn-beijing.volces.com
      url: https://company.static.mengma.cn
      sub_folder: 4c9ce6c89cff596b
      region: cn-beijing
      bucket_name: company-mengma
    organization:
      endpoint: https://tos-cn-beijing.volces.com
      url: https://company.static.mengma.cn
      sub_folder: 087fafc89a88450f
      region: cn-beijing
      bucket_name: company-mengma
    task:
      endpoint: https://tos-cn-beijing.volces.com
      url: https://company.static.mengma.cn
      sub_folder: 51824ad23cb50c1c
      region: cn-beijing
      bucket_name: company-mengma
company:
  default_company_id: 13
  material:
    default_company_material_library_name: 爆品库
  openDouyin:
    default_open_id: _000DJN2rftiAJKuHYasyawDeO9_E77gFAx9
service:
  douyin:
    endpoint: discovery:///mengma.douyin.service
  common:
    endpoint: discovery:///mengma.common.service
  weixin:
    endpoint: discovery:///mengma.weixin.service
  material:
    endpoint: discovery:///mengma.material.service
registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http
event:
  kafka:
    addr: 192.168.1.171:9092,192.168.2.95:9092,192.168.2.94:9092
    topic: product_test
